###################################################################################################
# +---------------------------------------------------------------------------------------------+ #
# |                                                                                             | #
# +---------------------------------------------------------------------------------------------+ #
###################################################################################################

# Default language of plugin
language: "en"

# Time format used for time string
# The following pattern letters are defined (all other characters from 'A' to 'Z' and from 'a' to 'z' are reserved):
# +--------+--------------------------------------------------+---------------------------------------+
# | Letter | Date or Time Component                           | Examples                              |
# +--------+--------------------------------------------------+---------------------------------------+
# | G      | Era designator                                   | AD                                    |
# | y      | Year                                             | 1996; 96                              |
# | Y      | Week year                                        | 2009; 09                              |
# | M      | Month in year                                    | July; Jul; 07                         |
# | w      | Week in year                                     | 27                                    |
# | W      | Week in month                                    | 2                                     |
# | D      | Day in year                                      | 189                                   |
# | d      | Day in month                                     | 10                                    |
# | F      | Day of week in month                             | 2                                     |
# | E      | Day name in week                                 | Tuesday; Tue                          |
# | u      | Day number of week (1 = Monday, ..., 7 = Sunday) | 1                                     |
# | a      | Am/pm marker                                     | PM                                    |
# | H      | Hour in day (0-23)                               | 0                                     |
# | k      | Hour in day (1-24)                               | 24                                    |
# | K      | Hour in am/pm (0-11)                             | 0                                     |
# | h      | Hour in am/pm (1-12)                             | 12                                    |
# | m      | Minute in hour                                   | 30                                    |
# | s      | Second in minute                                 | 55                                    |
# | S      | Millisecond                                      | 978                                   |
# | z      | Time zone                                        | Pacific Standard Time; PST; GMT-08:00 |
# | Z      | Time zone                                        | -0800                                 |
# | X      | Time zone                                        | -08; -0800; -08:00                    |
# +--------+--------------------------------------------------+---------------------------------------+
#
# More info at https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
date-format: "EEE, d MMM yyyy HH:mm:ss"

database:
  hostname: "localhost"
  port: 3306
  database: ""
  username: ""
  password: ""
  options:
    # Format
    #  option=value
    # be
    #  option: "value"
    #
    # More options at https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-configuration-properties.html
    #
    # Default:
    #   autoReconnect: "true"
    autoReconnect: "true"
  actions:
    # Save period to database (in seconds)
    # Warning with small value, server performances can be degraded
    #
    # Default: 60
    save-period: 60